#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   sudo ./set-static-ip.sh master   [--conf /path/cluster.conf]
#   sudo ./set-static-ip.sh worker1  [--conf /path/cluster.conf]
#   sudo ./set-static-ip.sh worker2  [--conf /path/cluster.conf]

ROLE="${1:-}"
shift || true
CONF_PATH="./cluster.conf"

usage() {
  echo "Usage: sudo $0 <master|worker1|worker2> [--conf /path/to/cluster.conf]"
  exit 1
}

need_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "[ERROR] Please run as root (sudo)." >&2
    exit 1
  fi
}

load_conf() {
  if [[ -f "${CONF_PATH}" ]]; then
    # shellcheck disable=SC1090
    source "${CONF_PATH}"
  else
    echo "[ERROR] cluster.conf not found: ${CONF_PATH}" >&2
    exit 1
  fi
}

valid_ipv4() {
  local ip="$1"
  [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  local o1 o2 o3 o4
  IFS='.' read -r o1 o2 o3 o4 <<<"$ip"
  for o in "$o1" "$o2" "$o3" "$o4"; do
    [[ "$o" -ge 0 && "$o" -le 255 ]] || return 1
  done
  return 0
}

detect_iface() {
  local iface
  iface="$(ip -4 route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
  [[ -n "${iface}" ]] && { echo "${iface}"; return 0; }
  iface="$(ip -o -4 addr show | awk '$2!="lo"{print $2; exit}')"
  [[ -n "${iface}" ]] && { echo "${iface}"; return 0; }
  echo ""
  return 1
}

detect_gateway() {
  ip -4 route show default 2>/dev/null | awk '{print $3; exit}'
}

backup_netplan() {
  mkdir -p /root/netplan-backup
  local ts
  ts="$(date +%Y%m%d-%H%M%S)"
  cp -a /etc/netplan "/root/netplan-backup/netplan-${ts}" 2>/dev/null || true
  echo "[INFO] Backup: /root/netplan-backup/netplan-${ts}"
}

ensure_ssh_service() {
  echo "[INFO] Ensuring SSH is installed and running..."
  apt-get update -y
  apt-get install -y openssh-server openssh-client

  systemctl enable ssh || true
  systemctl start ssh || true

  if ! systemctl is-active --quiet ssh; then
    echo "[ERROR] ssh service is not active. Run: systemctl status ssh" >&2
    exit 1
  fi
  echo "[INFO] SSH is active."
}

ensure_admin_user_sudo() {
  local user="${ADMIN_USER:-}"
  if [[ -z "${user}" ]]; then
    echo "[WARN] ADMIN_USER not set in cluster.conf; skip sudo setup."
    return 0
  fi
  if ! id "${user}" >/dev/null 2>&1; then
    echo "[ERROR] ADMIN_USER=${user} does not exist on this node. Create it during Ubuntu install." >&2
    exit 1
  fi
  echo "[INFO] Ensuring ${user} has passwordless sudo..."
  usermod -aG sudo "${user}" || true
  cat > "/etc/sudoers.d/99-${user}-nopasswd" <<EOF
${user} ALL=(ALL) NOPASSWD:ALL
EOF
  chmod 440 "/etc/sudoers.d/99-${user}-nopasswd"
}

set_hostname() {
  local newname="$1"
  echo "[INFO] Setting hostname: ${newname}"
  hostnamectl set-hostname "${newname}"

  if grep -qE '^\s*127\.0\.1\.1\s+' /etc/hosts; then
    sed -i "s/^\s*127\.0\.1\.1\s\+.*/127.0.1.1\t${newname}/" /etc/hosts
  else
    echo -e "127.0.1.1\t${newname}" >> /etc/hosts
  fi
}

write_netplan() {
  local iface="$1"
  local ip="$2"
  local cidr="$3"
  local gw="$4"
  local dns_csv="$5"

  local outfile="/etc/netplan/99-static-ip.yaml"
  local dns_yaml="[]"

  if [[ -n "${dns_csv}" ]]; then
    IFS=',' read -ra dns_arr <<<"${dns_csv}"
    local joined=""
    for d in "${dns_arr[@]}"; do
      d="$(echo "$d" | xargs)"
      [[ -z "$d" ]] && continue
      valid_ipv4 "$d" || { echo "[ERROR] Invalid DNS: $d" >&2; exit 1; }
      if [[ -z "$joined" ]]; then
        joined="\"$d\""
      else
        joined="${joined}, \"$d\""
      fi
    done
    dns_yaml="[${joined}]"
  fi

  cat > "${outfile}" <<EOF
# Generated by set-static-ip.sh (cluster.conf)
network:
  version: 2
  renderer: networkd
  ethernets:
    ${iface}:
      dhcp4: no
      addresses:
        - ${ip}/${cidr}
      routes:
        - to: default
          via: ${gw}
      nameservers:
        addresses: ${dns_yaml}
EOF

  chmod 600 "${outfile}"
  echo "[INFO] Wrote: ${outfile}"
}

apply_netplan() {
  echo "[WARN] Applying netplan (may disconnect SSH)..."
  netplan generate
  netplan apply
  echo "[INFO] Netplan applied."
}

# parse args
[[ "${ROLE}" == "master" || "${ROLE}" == "worker1" || "${ROLE}" == "worker2" ]] || usage
while [[ $# -gt 0 ]]; do
  case "$1" in
    --conf) CONF_PATH="${2:-}"; shift 2 ;;
    *) echo "[ERROR] Unknown arg: $1" >&2; usage ;;
  esac
done

main() {
  need_root
  load_conf

  # ensure ssh + sudo first (so master can later ssh into workers)
  ensure_ssh_service
  ensure_admin_user_sudo

  local host="" ip=""
  case "${ROLE}" in
    master)  host="${MASTER_HOST}";  ip="${MASTER_IP}" ;;
    worker1) host="${WORKER1_HOST}"; ip="${WORKER1_IP}" ;;
    worker2) host="${WORKER2_HOST}"; ip="${WORKER2_IP}" ;;
  esac

  [[ -n "${host}" && -n "${ip}" ]] || { echo "[ERROR] Missing host/ip mapping in cluster.conf" >&2; exit 1; }
  valid_ipv4 "${ip}" || { echo "[ERROR] Invalid IP in conf: ${ip}" >&2; exit 1; }

  local iface
  iface="$(detect_iface)" || true
  [[ -n "${iface}" ]] || { echo "[ERROR] Cannot detect interface. Ensure network is up." >&2; exit 1; }

  local cidr="${CIDR:-24}"
  local dns="${DNS:-8.8.8.8,114.114.114.114}"

  local gw="${GATEWAY:-}"
  if [[ -z "${gw}" ]]; then
    gw="$(detect_gateway)"
  fi
  if [[ -z "${gw}" ]]; then
    [[ -n "${NET_PREFIX:-}" ]] || { echo "[ERROR] NET_PREFIX missing and gateway not detected" >&2; exit 1; }
    gw="${NET_PREFIX}.2"
  fi
  valid_ipv4 "${gw}" || { echo "[ERROR] Invalid gateway: ${gw}" >&2; exit 1; }

  echo "[INFO] Using conf: ${CONF_PATH}"
  echo "[INFO] Role     : ${ROLE}"
  echo "[INFO] Hostname : ${host}"
  echo "[INFO] IFACE    : ${iface}"
  echo "[INFO] IP/CIDR  : ${ip}/${cidr}"
  echo "[INFO] GW       : ${gw}"
  echo "[INFO] DNS      : ${dns}"

  backup_netplan
  set_hostname "${host}"
  write_netplan "${iface}" "${ip}" "${cidr}" "${gw}" "${dns}"
  apply_netplan

  echo "[INFO] Current IP:"
  ip -4 addr show "${iface}" || true
  echo "[INFO] Default route:"
  ip -4 route show default || true
  echo "[INFO] Done."
}

main
